version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"  # Exposes Flask API on localhost:5000
    environment:
      - FLASK_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=your_username
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=stix_db
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"  # Exposes MySQL on localhost:3306
    volumes:
      - mysql_data:/var/lib/mysql

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"  # To interact with Selenium from the locahost
    depends_on:
      - flask-app

volumes:
  mysql_data:
