name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/compose-action@v2.1.0

    - name: Build and Run Services
      run: |
        docker-compose up -d --build
        docker-compose exec -T flask-app pytest ling508/tests --verbose

    - name: Tear down Docker Compose
      if: always()
      run: docker-compose down --volumes
